# Generated by Django 5.2.9 on 2025-12-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_admin_notes_order_estimated_delivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_signature',
            new_name='stripe_client_secret',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_order_id',
            new_name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('cod', 'Cash on Delivery')], default='stripe', max_length=20),
        ),
    ]
