# Generated by Django 5.2.9 on 2025-12-19 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productinteraction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbehaviorsummary',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='userbehaviorsummary',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailycategorystats',
            unique_together={('category', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyproductstats',
            unique_together={('product', 'date')},
        ),
        migrations.AddIndex(
            model_name='productinteraction',
            index=models.Index(fields=['product', 'interaction_type'], name='product_int_product_55bdf8_idx'),
        ),
        migrations.AddIndex(
            model_name='productinteraction',
            index=models.Index(fields=['created_at'], name='product_int_created_5e3bab_idx'),
        ),
        migrations.AddIndex(
            model_name='productinteraction',
            index=models.Index(fields=['user'], name='product_int_user_id_15e79d_idx'),
        ),
        migrations.AddIndex(
            model_name='productinteraction',
            index=models.Index(fields=['session_key'], name='product_int_session_80e525_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehaviorsummary',
            index=models.Index(fields=['product'], name='user_behavi_product_722610_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehaviorsummary',
            index=models.Index(fields=['viewed', 'purchased'], name='user_behavi_viewed_15b87c_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehaviorsummary',
            index=models.Index(fields=['added_to_cart', 'purchased'], name='user_behavi_added_t_8eb6f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbehaviorsummary',
            unique_together={('session_key', 'product'), ('user', 'product')},
        ),
    ]
